### ISSUE TITLE
Missing readme on the new spark note book (bronze2silver)

### ISSUE THREAD

**Issue by yodobrin** [Azure-Samples/sample-mdw-serverless#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> The readme does not include a section describing the new spark notebook, when should it be used etc.

### Any log messages given by the failure
> no this is a doc request

### Expected/desired behavior
> doc is updated

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by soferreira** [comment]
With the new linked services added to the code. Instructions to configure the new ls are also missing from readme
